### ISSUE TITLE
Angular 6, 7 - error TS1192: Module '".../node_modules/deepmerge/index"' has no default export.

### ISSUE THREAD

**Issue by luiscla27** [TehShrike/deepmerge#130]
Currently i see the following error:
![image](https://user-images.githubusercontent.com/29953012/50518586-ff2e7280-0a7b-11e9-8cbe-5f3d314d9459.png)

But it gets fixed when i change `index.d.ts` from this:
```
declare function deepmerge<T>(x: Partial<T>, y: Partial<T>, options?: deepmerge.Options): T;
declare function deepmerge<T1, T2>(x: Partial<T1>, y: Partial<T2>, options?: deepmerge.Options): T1 & T2;
declare namespace deepmerge {
	export interface Options {
		arrayMerge?(target: any[], source: any[], options?: Options): any[];
		clone?: boolean;
		isMergeableObject?(value: object): boolean;
	}

	export function all (objects: object[], options?: Options): object;
}
export = deepmerge;
```
To this (added **default** export):
```
declare function deepmerge<T>(x: Partial<T>, y: Partial<T>, options?: deepmerge.Options): T;
declare function deepmerge<T1, T2>(x: Partial<T1>, y: Partial<T2>, options?: deepmerge.Options): T1 & T2;
declare namespace deepmerge {
	export interface Options {
		arrayMerge?(target: any[], source: any[], options?: Options): any[];
		clone?: boolean;
		isMergeableObject?(value: object): boolean;
	}

	export function all (objects: object[], options?: Options): object;
}
export default deepmerge;
```

You may see a similar issue for another Angular component [here](https://github.com/gpbl/react-day-picker/pull/539) (react-day-picker)

**Comment by TehShrike** [comment]
Which version of deepmerge?

deepmerge 3.0.0 was released without an ESM export because [Webpack is broken](https://github.com/webpack/webpack/issues/6584).

Upgrade to deepmerge@3 and switch to `import * as deepmerge from 'deepmerge'` and everything should work correctly, including the type definitions.

**Comment by luiscla27** [comment]
Yup, upgrading to 3.0.0 fixed it, thank you @TehShrike :)
