### ISSUE TITLE
Is there an option for exclusive merge?

### ISSUE THREAD

**Issue by iomar9** [TehShrike/deepmerge#132]
Hi, is there an option in the library for exclusive deep merge, copying only those properties existing in obj1 from obj2 and discarding those who don't exist in obj1:
Example:
var obj1={"id":"0","name":"","favorite":{ "cars":[{"model":"","id":""}]} };
var obj2= {"id":"3","Job":"ssss","favorite":{ "cars":[{"model":"911","id":"1","color":"silver"},{"model":"enzo","id":"2","color":"red"}]}, account:{} };

Results:  
- properties that exist only in obj2 like job and color should not be copied, the account object should not be copied either
- properties and objects that exist only in obj1 can be copied or not, I don't care.
- the result should be:
 {"id":"3","favorite":{ "cars":[{"model":"911","id":"1"},{"model":"enzo","id":"2"}]} };

**Comment by RiZKiT** [comment]
I don't think so, but I could imagine two ways:
- if the number of properties you want to copy is low or the properties are already known, just copy the values one by one (yes a bit old school but works and is predictable)
- deep merge both objects and then recursively travel through the result object and delete all keys that aren't in the first object.

But normally one would ask, what is the reason to do this?

**Comment by iomar9** [comment]
Thanks RiZKiT.
The reason is that we have 2 objects, obj1 is like a schema, it has all the needed fields but with empty/dummy values. obj2 has the actual data + additional object and fields that should not be filled in obj1. None of The merge scripts I found have that option, (to exclude the additional objects fields in obj2).
Your 1st solution won't work since this is part of a generic function so neither of the objects structure is known beforehand.
The 2nd solution would actually work, can you please help me with this?

**Comment by TehShrike** [comment]
Are you imagining that restriction applied only at the top level (e.g. id, name, favorite) or all child objects too (e.g. model, color)?

**Comment by iomar9** [comment]
all child objects (including model and color)

**Comment by TehShrike** [comment]
@iomar9 deepmerge doesn't have any way to do that.  I would recommend forking this library and changing this: https://github.com/TehShrike/deepmerge/blob/155afde81937952385fdb72c6fd237b634c3971a/index.js#L27-L31

by wrapping the whole thing in a `if (key in target)` check.  That should add the behavior you want.

**Comment by TehShrike** [comment]
I'm not sure what problem you're describing.  You should create a [fiddle](https://jsfiddle.net/) that uses deepmerge to merge two objects, and add a comment with what output you expect the merge to return.  That will let us see what you are doing, what is happening, and what you expect to happen instead.

**Comment by iomar9** [comment]
These are 2 fiddles, I'm using the UMD version with the added condition, the script by the end contains the expectedOutcome:
-  https://jsfiddle.net/hLostj0k/2/
- commented some code to always call mergeObject: http://jsfiddle.net/uwjn7Le5/1/

**Comment by iomar9** [comment]
Never mind, I got it to work, thanks a lot @TehShrike  :)
