### ISSUE TITLE
merging change mongo's objectID structure

### ISSUE THREAD

**Issue by ValdoGhafoor** [TehShrike/deepmerge#136]
Hi ! 
I noticed that using deepmerge with an object that contains an objectID from mongoDB database change the structure of it. 

```
console.log({ _id: someIDObject });
```
```
output:
===> { _id: 5c4b38ba61709ad8be78fb00 }
```

looks fine, however the following code triggers error "object [{"_bsontype":"ObjectID","id":{"0":92,...,"11":0}}] is not a valid ObjectId" when I try to insert it in my DB

```
const merged = deepmerge({}, { _id: someIDObject });
console.log(merged)
```
```
output
===> { 
    _id: {
        _bsontype: 'ObjectID',
        id:  { 
          '0': 92,
          '1': 75,
          '2': 56,
          '3': 186,
          '4': 97,
          '5': 112,
          '6': 154,
          '7': 216,
          '8': 190,
          '9': 120,
          10': 251,
          '11': 0
         } 
     }
 }
```

**Comment by TehShrike** [comment]
Can you provide some code that can be tested/run?  Perhaps in a [fiddle](https://jsfiddle.net/)?

Bear in mind that any objects that are created with constructor functions will have their properties cloned onto a vanilla object that does not share the same prototype chain.
