### ISSUE TITLE
Error during merge

### ISSUE THREAD

**Issue by teamco** [TehShrike/deepmerge#141]
`asyncToGenerator.js:6`
`Uncaught (in promise) RangeError: Maximum call stack size exceeded`
    `at Function.keys (<anonymous>)`
    `at mergeObject (umd.js:56)`
    `at deepmerge (umd.js:84)`
    `at cloneUnlessOtherwiseSpecified (umd.js:34)`
    `at umd.js:63`
    `at Array.forEach (<anonymous>)`
    `at mergeObject (umd.js:61)`
    `at deepmerge (umd.js:84)`
    `at cloneUnlessOtherwiseSpecified (umd.js:34)`
    `at umd.js:39`
`asyncGeneratorStep @ asyncToGenerator.js:6`
`_throw @ asyncToGenerator.js:29`
`Promise.then (async)`
`asyncGeneratorStep @ asyncToGenerator.js:13`
`_next @ asyncToGenerator.js:25`
`(anonymous) @ asyncToGenerator.js:32`
`(anonymous) @ asyncToGenerator.js:21`

**Comment by TehShrike** [comment]
- what code produced the error?
- what were you expecting the output of that code to be?

If your data structure has cycles, deepmerge will not attempt to detect that.  You would have to pass in a custom [`isMergeableObject`](https://github.com/TehShrike/deepmerge#ismergeableobject) function to handle that.
