### ISSUE TITLE
IE 11 support?

### ISSUE THREAD

**Issue by halloleo** [TehShrike/deepmerge#154]
Unfortunately in my use case i have to support IE 11:

I use the `umd.js` file of deepmerge and it works perfectly in Firefox, but IE always says the function `deepmerge ` is 'undedfined'.

Any way to make it work in IE11?

**Comment by TehShrike** [comment]
I don't have access to IE11 at the moment.  Can you debug it to find out what's going on?

**Comment by halloleo** [comment]
Well, the problem was the global factory wrapping in `umd.js`. When iImoved the functions directly into the global scope, it started working. For the customisation values for `arrayMerge` and `customMerge` I had to write the functions in the `function <name> (...) {...}` form, not in the arrow form shown in the ReadMe - IE doesn't seem to understand the arrow form of functions. :-(

**Comment by TehShrike** [comment]
Right – deepmerge currently ships an ES5 bundle, which should work fine in IE11.  You won't be able to use the ES2015 examples from the readme in an ES5 environment, you'll need to write the equivalent ES5 code.

In theory the UMD pattern should work just fine in IE11/ES5.  If you can figure out something specific that is causing it not to work, lemme know

**Comment by halloleo** [comment]
When inlining `umd.js` I always got `deepmerge` as 'undefined' - that's all I know. Removing the factory wrapper worked.

**Comment by TehShrike** [comment]
okay then
