### ISSUE TITLE
Please keep `clone: false`

### ISSUE THREAD

**Issue by jlarmstrongiv** [TehShrike/deepmerge#157]
I just came back to this library after a time, and I didn’t realize the default for clone had been switched. I’m glad you included it in the README at the end, otherwise I wouldn’t have found it.

This change broke my code, but I’m glad you kept the clone option. Would you consider keeping `clone: false` functionality, rather than deprecating it? Shallow cloning is very useful, especially in react.

**Comment by macdja38** [comment]
The difference between `clone: false` and `clone: true` is that when true a new object is created, when false stuff is merged into the initial object passed, modifying it. Neither of them should change Shallow cloning vs deep cloning behaviour?

**Comment by jlarmstrongiv** [comment]
Ahh, thank you for the clarification 😃so I believe I should be using [extend-merge](https://www.npmjs.com/package/extend-merge) instead.  I appreciate your prompt response!

**Comment by macdja38** [comment]
@jlarmstrongiv I'm not sure but wouldn't simply using Object.assign meet your use case? eg
```js
let objectToBeModified = { a: "cat", b: "dog" };
Object.assign(objectToBeModified, { b: "chair", c: "table" });
console.log(objectToBeModified); // { a: 'cat', b: 'chair', c: 'table' }
```

**Comment by jlarmstrongiv** [comment]
@macdja38 Object.assign() and ...spread work, but it starts to get tedious for deeply nested objects.  For instance, 
```js
const newState = {
  ...state,
  results: {
    ...state.results,
    some: {
      ...state.results.some,
      deeplyNestedItem: {
        ...state.results.deeplyNestedItem,
        someProp: 'changed'
      }
    }
  }
}
```
I always try to keep my data structures flat, but I’m looking for a library to shallow merge it for me when that use case arrises.

**Comment by TehShrike** [comment]
How are you using the word "shallow"?  In this context, we would interpret it to mean that you only care about merging the properties of that top object, and you wouldn't be touching any of the nested objects.

**Comment by jlarmstrongiv** [comment]
@TehShrike 
For my use case, shallow merging involves changing a property while keeping [immutability](https://redux.js.org/recipes/using-object-spread-operator) in mind.  I care about merging the properties of the top object, but whichever nested property I change, the objects that holds that nested property need to be new objects.   

The two objects I would shallow merge from the example about would be:
```js
shallowMerge(state, {
  results: { some: { deeplyNestedItem: {someProp: 'changed'}}}
})
```

I wrote my own code for this operation, and fixed a few bugs for it.  I think it works, but I would rather use a more dependable library.
```js
export const shallowMerge = (oldState, updatedProperties) => {
  let newState = { ...oldState, };
  for (let key in updatedProperties) {
    newState[key] = updatedProperties[key];
    if (updatedProperties[key] !== null && typeof updatedProperties[key] === 'object') {
      newState[key] = updateObject((oldState[key] || {}), newState[key]);
    }
  }
  return newState;
};
```
