### ISSUE TITLE
IE 11 regression

### ISSUE THREAD

**Issue by oliviertassinari** [TehShrike/deepmerge#171]
IE 11 doesn't support Object.assign, #167 prevents IE 11 support outside of the box:

![Capture d’écran 2019-10-21 à 14 18 57](https://user-images.githubusercontent.com/3165635/67204523-f4c7d580-f40d-11e9-801e-715a9c6042ef.png)

It was first reported in https://github.com/mui-org/material-ui/issues/17908.

Reverting to v4.0.0 solves the problem.

**Comment by basslagter** [comment]
Yes, same issue here!

**Comment by TehShrike** [comment]
Published as 4.1.12

**Comment by oliviertassinari** [comment]
@TehShrike Thank you! I appreciate the reactivity and the care ❤️
