### ISSUE TITLE
Stack blown with deepmerge.all() using isMergeableObject

### ISSUE THREAD

**Issue by nonara** [TehShrike/deepmerge#206]
Hello. Thanks for your work on deepmerge!

When using `all` with `isMergeableObject` and a nested object, it blows the stack in an infinite recursion scenario.

Reproduction:

```js
deepmerge.all([ 
  { "headers": { "h1": "value", "h2": "value" } }, 
  { "b": 3 } 
], { isMergeableObject: () => true })
```

**Comment by TehShrike** [comment]
What would the fix be here, other than "fix your `isMergeableObject` implementation"?

**Comment by nonara** [comment]
Sorry for not being clear. The `isMergeableObject` implementation here is irrelevant. Any value causes this.

**Comment by nonara** [comment]
Ok. I had a look at the code. `isMergeableObject` is typed `isMergeableObject?(value: object): boolean`, so I assumed that it was only passing elements which had the `object` js type. It's actually passing primitives as well.

Adding a `typeof value === 'object'` check to `isMergeableObject` fixes the crash.

Might be worth it to change the call signature to `(value:any): boolean`

**Comment by TehShrike** [comment]
hmm, so that's an issue with the TS typings then
