### ISSUE TITLE
is-mergeable-object is a devDependency

### ISSUE THREAD

**Issue by lionel87** [TehShrike/deepmerge#230]
When I try to require your package I get an `Error: Cannot find module 'is-mergeable-object'` message.\
Is there any reason the `is-mergeable-object` package is included in the dev dependencies in your `package.json`?

**Comment by lionel87** [comment]
found my mistake. my bad, sorry. it should be a dev-dep as it is. my configuration tricked me.

**Comment by ruscon** [comment]
have the same issue

**Comment by TehShrike** [comment]
The only way that should happen is if your build step is messing up and including `./index.js` instead of respecting the `main` entry point in the `package.json`:

https://github.com/TehShrike/deepmerge/blob/7640d50c9d9dcd5a17a6e92fdca1bd6de9d9caf9/package.json#L18

**Comment by ruscon** [comment]
> The only way that should happen is if your build step is messing up and including `./index.js` instead of respecting the `main` entry point in the `package.json`:
> 
> https://github.com/TehShrike/deepmerge/blob/7640d50c9d9dcd5a17a6e92fdca1bd6de9d9caf9/package.json#L18

this can potentially happen when using esm
