### ISSUE TITLE
Deno?

### ISSUE THREAD

**Issue by martin-braun** [TehShrike/deepmerge#236]
Hi,

are there any plans to port deepmerge over to Deno? A consistent solution for both engines would be nice and should be possible without much additional maintaining, since Deno is just node on steroids. 

Cheers.

**Comment by RebeccaStevens** [comment]
We could possibly look into doing this as part of the next major.

@TehShrike I've got plenty of free time to get back into working on the next release. We should probably have another meeting and talk about were we were up to.

**Comment by TehShrike** [comment]
> are there any plans to port deepmerge over to Deno? A consistent solution for both engines would be nice and should be possible without much additional maintaining, since Deno is just node on steroids.

I have not used deno.  What changes would need to be made?

**Comment by TehShrike** [comment]
That is definitely a thing I could do
