### ISSUE TITLE
use recursive partial for type definitions

### ISSUE THREAD

**Issue by jonnytest1** [TehShrike/deepmerge#240]
```
export type RecursivePartial<T> = {
  [P in keyof T]?: T[P] extends (infer U)[]
    ? RecursivePartial<U>[]
    : T[P] extends object
      ? RecursivePartial<T[P]>
      : T[P];
};

```

this way subobjects can also be partial but need to have the correct types if provided

**Comment by RebeccaStevens** [comment]
The `Partial` type is planned to be removed completely in the next version (whenever that may happen). A much more in-depth merging is planned.

See https://github.com/TehShrike/deepmerge/pull/226, specifically the [types.ts](https://github.com/RebeccaStevens/fork-deepmerge/blob/typescript/src/types.ts) file for more details.
However,  the typings there may be a little out of date now. See [this alternative](https://github.com/RebeccaStevens/deepmerge-ts/blob/main/src/types/merging.ts#L81) for the latest work on the typings (currently release as [deepmerge-ts](https://www.npmjs.com/package/deepmerge-ts))
