### ISSUE TITLE
How to avoid array concatenation

### ISSUE THREAD

**Issue by wpoortman** [TehShrike/deepmerge#244]
So in my current situation, all the array are concatenated by default like the docs explain. Now I've been trying to write a custom 'arrayMerge' as an option to avoid it and just extend the array instead of gluing them after each other.

Current situation:
```js
deepmerge({
  purge: {
    content: [
      'a/path/to/my/file-a',
      'a/path/to/my/file-b'
    ]
  }
}, {
  purge: {
    content: [
      'a/path/to/my/file-c',
      'a/path/to/my/file-d'
    ]
  }
})
```

Should output:

```js
{
  purge: {
    content: [
      'a/path/to/my/file-c',
      'a/path/to/my/file-d',
      'a/path/to/my/file-c',
      'a/path/to/my/file-d'
    ]
  }
}
```

Can't figure this out... any solution?

**Comment by RebeccaStevens** [comment]
Is this what you want?

```ts
{
  arrayMerge: (target, source, options) => {
    const destination = source.slice();
    source.forEach((item, index) => {
      destination.push(item);
    });
    return destination;
  }
}
```

**Comment by wpoortman** [comment]
> I'm not sure what you mean. What's the difference between what it does by default and what you want?

My current deepmerge.all() returns:

```js
{
  purge: {
    content: [
      'a/path/to/my/file-ca/path/to/my/file-da/path/to/my/file-ca/path/to/my/file-d'
    ]
  }
}
```

Instead of:

```js
{
  purge: {
    content: [
      'a/path/to/my/file-c',
      'a/path/to/my/file-d',
      'a/path/to/my/file-c',
      'a/path/to/my/file-d'
    ]
  }
}
```

**Comment by RebeccaStevens** [comment]
oh, the strings are getting concatenated together.
What does your `arrayMerge` function look like?

**Comment by wpoortman** [comment]
Currently no options are included, so the default of `deepmerge.all()`

**Comment by RebeccaStevens** [comment]
I'm not able to create the issue: https://codesandbox.io/s/stupefied-matan-df2ri6?file=/src/index.ts

**Comment by RebeccaStevens** [comment]
I'm not sure what might be causing this issue. You could try using my library instead and see if you are having the same issue with it: https://www.npmjs.com/package/deepmerge-ts

Note: deepmerge-ts was originally planned to be the next version of this library.

**Comment by wpoortman** [comment]
Which function in your lib would replace the `.all()` method?

**Comment by wpoortman** [comment]
And deepmerge a object with an object? For some reason I can't figure out this API 😄

I have two situations:
1. Merge a array of objects
2. Merge an object with the result of 1

Note: Previously I would do `deepmerge(deepmerge.all(myArray.map((extension) => {})), MyBaseObject)`

**Comment by RebeccaStevens** [comment]
So for 1. - Merging an array of objects into a single object, would just be `deepmerge(...myArrayOfObjects)`.

I'm not sure what you mean by 2. but if it is just that line of code, the equivalent would be:
`deepmerge(...(myArray.map((extension) => {})), MyBaseObject)`

**Comment by RebeccaStevens** [comment]
If you link me your code, I can take a look at it for you.

**Comment by wpoortman** [comment]
https://pastebin.com/qJ5c1j1c

The themes.json looks like:
```json
{
  "extensions": [
    {
      "name": "package-a",
      "src": "vendor/internal/package-a/src"
    },
    {
      "name": "package-b",
      "src": "vendor/internal/package-b/src"
    }
  ]
}
```

And a custom tailwind.config.js inside of one of those paths:
```js
module.exports = {
    purge: {
        content: [
            '/view/frontend/templates/**/*.phtml',
        ]
    }
}
```

Put a lot of time in this... almost at a point where I'm just telling myself to use the fix and move on haha

**Comment by RebeccaStevens** [comment]
Does this work for you?

```ts
return deepmerge(
  ...themeConfig.extensions.map((extension) => {
    const configFilePath = themeDirBackTrails[backtrail] + extension.src + "/tailwind.config.js";

    if (fs.existsSync(configFilePath)) {
      return require(configFilePath);
    }

    return {};
  }),
  baseConfig
);
```

**Comment by RebeccaStevens** [comment]
If you're able to provide more data I'll look into it more tomorrow.

**Comment by RebeccaStevens** [comment]
@wpoortman email me at rebecca.stevens@outlook.co.nz

**Comment by TehShrike** [comment]
To get more help you would need to provide a REPL link that replicates your problem, and demonstrates the output that you expect as opposed to what the code produces
