### ISSUE TITLE
Possible to remove duplicate objects in arrays?

### ISSUE THREAD

**Issue by basickarl** [TehShrike/deepmerge#251]
As the title stated is it possible to remove duplicate array objects when deep merging? I am referring to identical objects with identical values.

I tried the arrayMerge but that really isn't what I'm looking for, I'd like any array no matter how nested to figure this out automatically.

**Comment by TehShrike** [comment]
You can pass in a custom `arrayMerge` function that combines the arrays in the source and target however you like.  https://github.com/TehShrike/deepmerge#arraymerge
